import type { Metadata } from "next";
import "../globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { QueryProvider } from "@/providers/QueryProvider";
import { Toaster } from "sonner";
import { LensiProvider } from "@/providers/LenisProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {/* <Toaster />
        <QueryProvider>
          <LensiProvider>
            <Header />
            {children}
            <Footer />
          </LensiProvider>
        </QueryProvider> */}
      </body>
    </html>
  );
}
